# Generated by Django 5.1.2 on 2024-11-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoPosGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano_conclusao', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Especialização', 'Especialização'), ('Residência', 'Residência'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-doutorado', 'Pós-doutorado')], max_length=50)),
                ('instituicao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('Mulher Cisgênero', 'Mulher Cisgênero'), ('Mulher Transexual', 'Mulher Transexual'), ('Homem Cisgênero', 'Homem Cisgênero'), ('Homem Transexual', 'Homem Transexual'), ('Não Binário', 'Não Binário'), ('Prefiro não responder', 'Prefiro não responder'), ('Não sei', 'Não sei'), ('Outro', 'Outro')], max_length=50)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(choices=[('Brasileiro(a)', 'Brasileiro(a)'), ('Estrangeiro', 'Estrangeiro')], max_length=50)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('cor_raca', models.CharField(choices=[('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Não sei', 'Não sei'), ('Prefiro não responder', 'Prefiro não responder')], max_length=50)),
                ('pessoa_com_deficiencia', models.BooleanField(default=False)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('União Estável', 'União Estável')], max_length=50)),
                ('estado_residencia', models.CharField(max_length=2)),
                ('municipio_residencia', models.CharField(max_length=255)),
                ('instituicao_graduacao', models.CharField(max_length=255)),
                ('curso_graduacao', models.CharField(max_length=255)),
                ('ano_conclusao_graduacao', models.IntegerField()),
                ('possui_pos_graduacao', models.BooleanField(default=False)),
                ('atualmente_empregado', models.BooleanField(default=False)),
                ('emprego_atual', models.CharField(blank=True, max_length=255, null=True)),
                ('area_atuacao', models.CharField(max_length=255)),
                ('entrou_mercado_trabalho_12_meses', models.BooleanField(default=False)),
                ('situacao_atual', models.CharField(choices=[('Empregado na área de formação', 'Empregado na área de formação'), ('Empregado em área distinta', 'Empregado em área distinta'), ('Não estou empregado', 'Não estou empregado')], max_length=50)),
                ('media_salarial', models.CharField(choices=[('até 1 salário mínimo', 'até 1 salário mínimo'), ('entre 1 e 3 salários mínimos', 'entre 1 e 3 salários mínimos'), ('entre 4 e 7 salários mínimos', 'entre 4 e 7 salários mínimos'), ('mais que 7 salários mínimos', 'mais que 7 salários mínimos')], max_length=50)),
                ('posicao_gestao', models.BooleanField(default=False)),
                ('funcao_gestao', models.CharField(blank=True, max_length=255, null=True)),
                ('instituicao_gestao', models.CharField(blank=True, max_length=255, null=True)),
                ('publicacoes_orientador', models.CharField(choices=[('Não', 'Não'), ('Sim, de 1 a 2 publicações', 'Sim, de 1 a 2 publicações'), ('Sim, de 3 a 5 publicações', 'Sim, de 3 a 5 publicações'), ('Sim, mais de 5 publicações', 'Sim, mais de 5 publicações')], max_length=50)),
                ('cursos_pos_graduacao', models.ManyToManyField(blank=True, to='egressos.cursoposgraduacao')),
            ],
            options={
                'verbose_name': 'Egresso',
                'verbose_name_plural': 'Egressos',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=255)),
                ('nota', models.IntegerField(choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Regular'), (4, 'Bom'), (5, 'Ótimo')])),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_curso', to='egressos.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadePosConclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('Eventos Científicos', 'Participação em eventos científicos'), ('Livros/Capítulos', 'Publicação de Livro(s) e/ou Capítulos'), ('Patentes/Softwares', 'Desenvolvimento de patentes ou softwares'), ('Prêmios', 'Recebimento de prêmios científicos ou profissionais'), ('Rede de Pesquisa', 'Colaboração em redes de pesquisa'), ('Políticas/Práticas', 'Contribuição para políticas e práticas')], max_length=50)),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_pos_conclusao', to='egressos.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='MotivacaoPosGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('Aumento salarial através da titulação', 'Aumento salarial através da titulação'), ('Possibilidade de reconhecimento e progressão profissional', 'Possibilidade de reconhecimento e progressão profissional'), ('Recomendação da instituição de vínculo de trabalho', 'Recomendação da instituição de vínculo de trabalho'), ('Interesse em melhor qualificação profissional', 'Interesse em melhor qualificação profissional'), ('Expansão das atividades para outros campos', 'Expansão das atividades para outros campos'), ('Não se aplica (ensino, pesquisa e extensão)', 'Não se aplica (ensino, pesquisa e extensão)')], max_length=255)),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivacoes', to='egressos.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_programa', models.CharField(choices=[('Iniciação Científica e/ou Tecnológica', 'Iniciação Científica e/ou Tecnológica'), ('Extensão', 'Extensão'), ('Ensino', 'Ensino'), ('Monitoria', 'Monitoria')], max_length=50)),
                ('bolsista', models.BooleanField(default=False)),
                ('agencia_fomentadora', models.CharField(blank=True, choices=[('CNPq', 'CNPq'), ('CAPES', 'CAPES'), ('FAPEPI', 'FAPEPI'), ('UFDPar', 'UFDPar'), ('Outra', 'Outra')], max_length=50, null=True)),
                ('especificar_agencia', models.CharField(blank=True, max_length=255, null=True)),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_participacao', to='egressos.egresso')),
            ],
        ),
    ]
